// <auto-generated />
using System;
using AlitasGoWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlitasGoWeb.Migrations
{
    [DbContext(typeof(AlitasGoDbContext))]
    [Migration("20260912031839_InsercionValores")]
    partial class InsercionValores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlitasGoWeb.Models.CanalAtencion", b =>
                {
                    b.Property<int>("IdCanalAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCanalAtencion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCanalAtencion");

                    b.ToTable("CanalesAtencion", (string)null);

                    b.HasData(
                        new
                        {
                            IdCanalAtencion = 1,
                            Activo = true,
                            Nombre = "Salon"
                        },
                        new
                        {
                            IdCanalAtencion = 2,
                            Activo = true,
                            Nombre = "Delivery"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CanalPromocion", b =>
                {
                    b.Property<int>("IdCanalPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCanalPromocion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCanalPromocion");

                    b.ToTable("CanalesPromocion", (string)null);

                    b.HasData(
                        new
                        {
                            IdCanalPromocion = 1,
                            Activo = true,
                            Nombre = "Salon"
                        },
                        new
                        {
                            IdCanalPromocion = 2,
                            Activo = true,
                            Nombre = "Delivery"
                        },
                        new
                        {
                            IdCanalPromocion = 3,
                            Activo = true,
                            Nombre = "Todos"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoriaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoriaProducto");

                    b.ToTable("CategoriasProducto", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoriaProducto = 1,
                            Activo = true,
                            Nombre = "Alitas"
                        },
                        new
                        {
                            IdCategoriaProducto = 2,
                            Activo = true,
                            Nombre = "Boneless"
                        },
                        new
                        {
                            IdCategoriaProducto = 3,
                            Activo = true,
                            Nombre = "Guarniciones"
                        },
                        new
                        {
                            IdCategoriaProducto = 4,
                            Activo = true,
                            Nombre = "Bebidas"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Activo = true,
                            ApellidoMaterno = "Gomez",
                            ApellidoPaterno = "Perez",
                            DNI = "12345678",
                            Nombre = "Juan"
                        },
                        new
                        {
                            IdCliente = 2,
                            Activo = true,
                            ApellidoMaterno = "Diaz",
                            ApellidoPaterno = "Lopez",
                            DNI = "87654321",
                            Nombre = "Maria"
                        },
                        new
                        {
                            IdCliente = 3,
                            Activo = true,
                            ApellidoMaterno = "Torres",
                            ApellidoPaterno = "Ramirez",
                            DNI = "11223344",
                            Nombre = "Carlos"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ComboProducto", b =>
                {
                    b.Property<int>("IdProductoCombo")
                        .HasColumnType("int");

                    b.Property<int>("IdProductoComponente")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdSabor")
                        .HasColumnType("int");

                    b.HasKey("IdProductoCombo", "IdProductoComponente");

                    b.HasIndex("IdProductoComponente");

                    b.HasIndex("IdSabor");

                    b.ToTable("ComboProductos", (string)null);

                    b.HasData(
                        new
                        {
                            IdProductoCombo = 13,
                            IdProductoComponente = 2,
                            Cantidad = 2,
                            IdSabor = 1
                        },
                        new
                        {
                            IdProductoCombo = 13,
                            IdProductoComponente = 9,
                            Cantidad = 2
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CompraInsumos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ComprasInsumos", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.DetalleCompraInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("InsumoId");

                    b.ToTable("DetallesCompraInsumo", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdSabor")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSabor");

                    b.ToTable("DetallesPedido", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Dia", b =>
                {
                    b.Property<int>("IdDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDia");

                    b.ToTable("Dias", (string)null);

                    b.HasData(
                        new
                        {
                            IdDia = 1,
                            Activo = true,
                            Nombre = "Lunes"
                        },
                        new
                        {
                            IdDia = 2,
                            Activo = true,
                            Nombre = "Martes"
                        },
                        new
                        {
                            IdDia = 3,
                            Activo = true,
                            Nombre = "Miercoles"
                        },
                        new
                        {
                            IdDia = 4,
                            Activo = true,
                            Nombre = "Jueves"
                        },
                        new
                        {
                            IdDia = 5,
                            Activo = true,
                            Nombre = "Viernes"
                        },
                        new
                        {
                            IdDia = 6,
                            Activo = true,
                            Nombre = "Sabado"
                        },
                        new
                        {
                            IdDia = 7,
                            Activo = true,
                            Nombre = "Domingo"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.EstadoPedido", b =>
                {
                    b.Property<int>("IdEstadoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoPedido"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoPedido");

                    b.ToTable("EstadosPedido", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoPedido = 1,
                            Activo = true,
                            Nombre = "Recibido"
                        },
                        new
                        {
                            IdEstadoPedido = 2,
                            Activo = true,
                            Nombre = "EnPreparacion"
                        },
                        new
                        {
                            IdEstadoPedido = 3,
                            Activo = true,
                            Nombre = "Listo"
                        },
                        new
                        {
                            IdEstadoPedido = 4,
                            Activo = true,
                            Nombre = "EnReparto"
                        },
                        new
                        {
                            IdEstadoPedido = 5,
                            Activo = true,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            IdEstadoPedido = 6,
                            Activo = true,
                            Nombre = "Anulado"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Insumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInsumo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdInsumo");

                    b.ToTable("Insumos", (string)null);

                    b.HasData(
                        new
                        {
                            IdInsumo = 1,
                            Nombre = "Alitas crudas",
                            StockActual = 20m,
                            StockMinimo = 5m,
                            UnidadMedida = "kg"
                        },
                        new
                        {
                            IdInsumo = 2,
                            Nombre = "Salsa buffalo",
                            StockActual = 5m,
                            StockMinimo = 2m,
                            UnidadMedida = "lt"
                        },
                        new
                        {
                            IdInsumo = 3,
                            Nombre = "Salsa BBQ",
                            StockActual = 4m,
                            StockMinimo = 2m,
                            UnidadMedida = "lt"
                        },
                        new
                        {
                            IdInsumo = 4,
                            Nombre = "Gaseosa personal",
                            StockActual = 50m,
                            StockMinimo = 12m,
                            UnidadMedida = "unidad"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.NroMesa", b =>
                {
                    b.Property<int>("IdNroMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNroMesa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdZonaLocal")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("IdNroMesa");

                    b.HasIndex("IdZonaLocal");

                    b.ToTable("Mesas", (string)null);

                    b.HasData(
                        new
                        {
                            IdNroMesa = 1,
                            Activo = true,
                            IdZonaLocal = 1,
                            NumeroMesa = 1
                        },
                        new
                        {
                            IdNroMesa = 2,
                            Activo = true,
                            IdZonaLocal = 1,
                            NumeroMesa = 2
                        },
                        new
                        {
                            IdNroMesa = 3,
                            Activo = true,
                            IdZonaLocal = 1,
                            NumeroMesa = 3
                        },
                        new
                        {
                            IdNroMesa = 4,
                            Activo = true,
                            IdZonaLocal = 1,
                            NumeroMesa = 4
                        },
                        new
                        {
                            IdNroMesa = 5,
                            Activo = true,
                            IdZonaLocal = 1,
                            NumeroMesa = 5
                        },
                        new
                        {
                            IdNroMesa = 6,
                            Activo = true,
                            IdZonaLocal = 2,
                            NumeroMesa = 6
                        },
                        new
                        {
                            IdNroMesa = 7,
                            Activo = true,
                            IdZonaLocal = 2,
                            NumeroMesa = 7
                        },
                        new
                        {
                            IdNroMesa = 8,
                            Activo = true,
                            IdZonaLocal = 2,
                            NumeroMesa = 8
                        },
                        new
                        {
                            IdNroMesa = 9,
                            Activo = true,
                            IdZonaLocal = 2,
                            NumeroMesa = 9
                        },
                        new
                        {
                            IdNroMesa = 10,
                            Activo = true,
                            IdZonaLocal = 2,
                            NumeroMesa = 10
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Pago", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCanalAtencion")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCanalAtencion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoPedido");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.PedidoDelivery", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdZonaDelivery")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdZonaDelivery");

                    b.ToTable("PedidosDelivery", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.PedidoLocal", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdNroMesa")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdNroMesa");

                    b.ToTable("PedidosLocal", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCategoriaProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiereSabor")
                        .HasColumnType("bit");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoriaProducto");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Activo = true,
                            Descripcion = "Media docena de alitas",
                            IdCategoriaProducto = 1,
                            IdTipoProducto = 1,
                            Nombre = "Media Docena Alitas",
                            Precio = 18.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            IdProducto = 2,
                            Activo = true,
                            Descripcion = "Docena de alitas",
                            IdCategoriaProducto = 1,
                            IdTipoProducto = 1,
                            Nombre = "Docena Alitas",
                            Precio = 30.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            IdProducto = 3,
                            Activo = true,
                            Descripcion = "Dos docenas de alitas",
                            IdCategoriaProducto = 1,
                            IdTipoProducto = 1,
                            Nombre = "2 Docenas Alitas",
                            Precio = 55.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            IdProducto = 4,
                            Activo = true,
                            Descripcion = "Media docena boneless",
                            IdCategoriaProducto = 2,
                            IdTipoProducto = 1,
                            Nombre = "Media Docena Boneless",
                            Precio = 20.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            IdProducto = 5,
                            Activo = true,
                            Descripcion = "Docena boneless",
                            IdCategoriaProducto = 2,
                            IdTipoProducto = 1,
                            Nombre = "Docena Boneless",
                            Precio = 35.00m,
                            RequiereSabor = true
                        },
                        new
                        {
                            IdProducto = 6,
                            Activo = true,
                            Descripcion = "Porcion de papas",
                            IdCategoriaProducto = 3,
                            IdTipoProducto = 3,
                            Nombre = "Papas Fritas",
                            Precio = 8.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 7,
                            Activo = true,
                            Descripcion = "Porcion de yucas",
                            IdCategoriaProducto = 3,
                            IdTipoProducto = 3,
                            Nombre = "Yucas Fritas",
                            Precio = 9.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 8,
                            Activo = true,
                            Descripcion = "Ensalada fresca",
                            IdCategoriaProducto = 3,
                            IdTipoProducto = 3,
                            Nombre = "Ensalada",
                            Precio = 7.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 9,
                            Activo = true,
                            Descripcion = "Gaseosa 500ml",
                            IdCategoriaProducto = 4,
                            IdTipoProducto = 2,
                            Nombre = "Gaseosa Personal",
                            Precio = 5.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 10,
                            Activo = true,
                            Descripcion = "Gaseosa 1.5L",
                            IdCategoriaProducto = 4,
                            IdTipoProducto = 2,
                            Nombre = "Gaseosa 1.5L",
                            Precio = 12.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 11,
                            Activo = true,
                            Descripcion = "Vaso de chicha",
                            IdCategoriaProducto = 4,
                            IdTipoProducto = 2,
                            Nombre = "Chicha Vaso",
                            Precio = 4.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 12,
                            Activo = true,
                            Descripcion = "Jarra de chicha",
                            IdCategoriaProducto = 4,
                            IdTipoProducto = 2,
                            Nombre = "Chicha Jarra 1L",
                            Precio = 10.00m,
                            RequiereSabor = false
                        },
                        new
                        {
                            IdProducto = 13,
                            Activo = true,
                            Descripcion = "2 docenas + 2 gaseosas personales",
                            IdCategoriaProducto = 1,
                            IdTipoProducto = 4,
                            Nombre = "Combo Duo Alitas",
                            Precio = 65.00m,
                            RequiereSabor = false
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdCanalPromocion")
                        .HasColumnType("int");

                    b.Property<int>("IdDia")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPromocion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPromocion");

                    b.HasIndex("IdCanalPromocion");

                    b.HasIndex("IdDia");

                    b.HasIndex("IdTipoPromocion");

                    b.ToTable("Promociones", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Receta", b =>
                {
                    b.Property<int>("IdProductoInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoInsumo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadUsada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdSabor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProductoInsumo");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSabor");

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Sabor", b =>
                {
                    b.Property<int>("IdSabor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSabor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdSabor");

                    b.ToTable("Sabores", (string)null);

                    b.HasData(
                        new
                        {
                            IdSabor = 1,
                            Activo = true,
                            Nombre = "Buffalo"
                        },
                        new
                        {
                            IdSabor = 2,
                            Activo = true,
                            Nombre = "BBQ"
                        },
                        new
                        {
                            IdSabor = 3,
                            Activo = true,
                            Nombre = "Acevichada"
                        },
                        new
                        {
                            IdSabor = 4,
                            Activo = true,
                            Nombre = "Maracuya"
                        },
                        new
                        {
                            IdSabor = 5,
                            Activo = true,
                            Nombre = "Ajo Parmesano"
                        },
                        new
                        {
                            IdSabor = 6,
                            Activo = true,
                            Nombre = "Honey Mustard"
                        },
                        new
                        {
                            IdSabor = 7,
                            Activo = true,
                            Nombre = "Atomica"
                        },
                        new
                        {
                            IdSabor = 8,
                            Activo = true,
                            Nombre = "Picante"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoPago", b =>
                {
                    b.Property<int>("IdTipoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPago"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoPago");

                    b.ToTable("TiposPago", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoPago = 1,
                            Activo = true,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            IdTipoPago = 2,
                            Activo = true,
                            Nombre = "Yape"
                        },
                        new
                        {
                            IdTipoPago = 3,
                            Activo = true,
                            Nombre = "Tarjeta"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoProducto", b =>
                {
                    b.Property<int>("IdTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdTipoProducto");

                    b.ToTable("TiposProducto", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoProducto = 1,
                            Activo = true,
                            Nombre = "Plato"
                        },
                        new
                        {
                            IdTipoProducto = 2,
                            Activo = true,
                            Nombre = "Bebida"
                        },
                        new
                        {
                            IdTipoProducto = 3,
                            Activo = true,
                            Nombre = "Guarnicion"
                        },
                        new
                        {
                            IdTipoProducto = 4,
                            Activo = true,
                            Nombre = "Combo"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoPromocion", b =>
                {
                    b.Property<int>("IdTipoPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPromocion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoPromocion");

                    b.ToTable("TiposPromocion", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoPromocion = 1,
                            Activo = true,
                            Codigo = "NORMAL",
                            Nombre = "Precio normal"
                        },
                        new
                        {
                            IdTipoPromocion = 2,
                            Activo = true,
                            Codigo = "DOCENA",
                            Nombre = "Promocion docena"
                        },
                        new
                        {
                            IdTipoPromocion = 3,
                            Activo = true,
                            Codigo = "2X1",
                            Nombre = "Promocion 2x1"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ZonaDelivery", b =>
                {
                    b.Property<int>("IdZonaDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZonaDelivery"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoDelivery")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("NombreZona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZonaDelivery");

                    b.ToTable("ZonasDelivery", (string)null);

                    b.HasData(
                        new
                        {
                            IdZonaDelivery = 1,
                            Activo = true,
                            CostoDelivery = 3.00m,
                            NombreZona = "Cerca"
                        },
                        new
                        {
                            IdZonaDelivery = 2,
                            Activo = true,
                            CostoDelivery = 5.00m,
                            NombreZona = "Media"
                        },
                        new
                        {
                            IdZonaDelivery = 3,
                            Activo = true,
                            CostoDelivery = 8.00m,
                            NombreZona = "Bordes"
                        });
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ZonaLocal", b =>
                {
                    b.Property<int>("IdZonaLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZonaLocal"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZonaLocal");

                    b.ToTable("ZonasLocal", (string)null);

                    b.HasData(
                        new
                        {
                            IdZonaLocal = 1,
                            Activo = true,
                            Nombre = "Interior"
                        },
                        new
                        {
                            IdZonaLocal = 2,
                            Activo = true,
                            Nombre = "Vereda"
                        });
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.Property<int>("ProductosIdProducto")
                        .HasColumnType("int");

                    b.Property<int>("PromocionesIdPromocion")
                        .HasColumnType("int");

                    b.HasKey("ProductosIdProducto", "PromocionesIdPromocion");

                    b.HasIndex("PromocionesIdPromocion");

                    b.ToTable("PromocionProducto", (string)null);
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ComboProducto", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Producto", "ProductoCombo")
                        .WithMany("Componentes")
                        .HasForeignKey("IdProductoCombo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Producto", "ProductoComponente")
                        .WithMany("ComponenteDe")
                        .HasForeignKey("IdProductoComponente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Sabor", "Sabor")
                        .WithMany("ComboProductos")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductoCombo");

                    b.Navigation("ProductoComponente");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.DetalleCompraInsumo", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.CompraInsumos", "CompraInsumos")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Insumo", "Insumo")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraInsumos");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.DetallePedido", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Producto", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Sabor", "Sabor")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Producto");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.NroMesa", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.ZonaLocal", "ZonaLocal")
                        .WithMany("Mesas")
                        .HasForeignKey("IdZonaLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZonaLocal");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Pago", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Pedido", "Pedido")
                        .WithOne("Pago")
                        .HasForeignKey("AlitasGoWeb.Models.Pago", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.TipoPago", "TipoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("TipoPago");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Pedido", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.CanalAtencion", "CanalAtencion")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCanalAtencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.EstadoPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstadoPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanalAtencion");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoPedido");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.PedidoDelivery", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Pedido", "Pedido")
                        .WithOne("PedidoDelivery")
                        .HasForeignKey("AlitasGoWeb.Models.PedidoDelivery", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.ZonaDelivery", "ZonaDelivery")
                        .WithMany("PedidosDelivery")
                        .HasForeignKey("IdZonaDelivery")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("ZonaDelivery");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.PedidoLocal", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.NroMesa", "NroMesa")
                        .WithMany("PedidosLocales")
                        .HasForeignKey("IdNroMesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Pedido", "Pedido")
                        .WithOne("PedidoLocal")
                        .HasForeignKey("AlitasGoWeb.Models.PedidoLocal", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NroMesa");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Producto", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoriaProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProducto");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Promocion", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.CanalPromocion", "CanalPromocion")
                        .WithMany("Promociones")
                        .HasForeignKey("IdCanalPromocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Dia", "Dia")
                        .WithMany("Promociones")
                        .HasForeignKey("IdDia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.TipoPromocion", "TipoPromocion")
                        .WithMany("Promociones")
                        .HasForeignKey("IdTipoPromocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanalPromocion");

                    b.Navigation("Dia");

                    b.Navigation("TipoPromocion");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Receta", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Insumo", "Insumo")
                        .WithMany("ProductoInsumos")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Producto", "Producto")
                        .WithMany("ProductoInsumos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Sabor", "Sabor")
                        .WithMany("Recetas")
                        .HasForeignKey("IdSabor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Insumo");

                    b.Navigation("Producto");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.HasOne("AlitasGoWeb.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlitasGoWeb.Models.Promocion", null)
                        .WithMany()
                        .HasForeignKey("PromocionesIdPromocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CanalAtencion", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CanalPromocion", b =>
                {
                    b.Navigation("Promociones");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.CompraInsumos", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Dia", b =>
                {
                    b.Navigation("Promociones");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Insumo", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("ProductoInsumos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.NroMesa", b =>
                {
                    b.Navigation("PedidosLocales");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Pago");

                    b.Navigation("PedidoDelivery");

                    b.Navigation("PedidoLocal");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Producto", b =>
                {
                    b.Navigation("ComponenteDe");

                    b.Navigation("Componentes");

                    b.Navigation("DetallePedidos");

                    b.Navigation("ProductoInsumos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.Sabor", b =>
                {
                    b.Navigation("ComboProductos");

                    b.Navigation("DetallePedidos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.TipoPromocion", b =>
                {
                    b.Navigation("Promociones");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ZonaDelivery", b =>
                {
                    b.Navigation("PedidosDelivery");
                });

            modelBuilder.Entity("AlitasGoWeb.Models.ZonaLocal", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
